version: "3"

services:
    eurostat:
      build:
        context: .
      ports:
        - "8000:8000"
      env_file:
        - .env
      depends_on:
        - mysql

    mysql:
      image: mysql:5.7
      volumes:
        - ./docker/mysql/:/docker-entrypoint-initdb.d
      env_file:
        - .env
