version: "3"

services:
    eurostat:
      build:
        context: .
      ports:
        - "8000:8000"

    mysql:
      image: mysql:5.7
      ports:
        - "3306:3306"
      volumes:
        - ./docker/mysql/house:/docker-entrypoint-initdb.d
      env_file:
        - .env
